name: Build artifacts

on:
  workflow_dispatch:
    inputs:
      arch:
        description: "Target architecture"
        required: true
        type: choice
        default: aarch64
        options:
          - aarch64
          - x86_64

jobs:
  build-artifacts:
    if: ${{ matrix.arch == github.event.inputs.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        arch: [aarch64, x86_64]
        include:
          - arch: aarch64
            runner: ubuntu-2204-32-cores-arm
            artifact_name: libgreptimedb-client-cpp-ffi-aarch64-linux
          - arch: x86_64
            runner: ubuntu-22.04
            artifact_name: libgreptimedb-client-cpp-ffi-x86_64-linux
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      - name: Build artifacts
        uses: docker/build-push-action@v3
        env:
          BUILDKIT_PROGRESS: plain
        with:
          file: ./docker/package/Dockerfile
          push: false
          provenance: false
          outputs: type=local,dest=./build/bins

      - name: Pack artifacts
        shell: bash
        run: |
          mkdir bins
          cp ./build/bins/libgreptimedb_client_cpp_ffi.so bins
          cp ./cpp/src/greptime.h bins

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./bins
