name: Build artifacts

on:
  workflow_dispatch:

jobs:
  build-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-2204-32-cores-arm ]
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      - name: Build artifacts
        uses: docker/build-push-action@v3
        env:
          BUILDKIT_PROGRESS: plain
        with:
          file: ./docker/package/Dockerfile
          push: false
          provenance: false
          outputs: type=local,dest=./build/bins

      - name: Pack artifacts
        shell: bash
        run: |
          mkdir bins
          cp ./build/bins/libgreptimedb_client_cpp_ffi.so bins
          cp ./cpp/src/greptime.h bins

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libgreptimedb-client-cpp-ffi-aarch64-linux
          path: ./bins
